version: "3.9"
services:
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089

  worker:
    image: locustio/locust
    volumes:
      - ./locust:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --worker --master-host master

  postgres:
    container_name: postgres_container
    image: postgres:13.0
    command:
      - "postgres"
    environment:
      POSTGRES_DB: "test_pg"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U admin -d test_pg -h localhost"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
